### ISSUE TITLE
Where do I edit the footer?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#107]
![screen shot 2015-04-02 at 16 48 26](https://cloud.githubusercontent.com/assets/7487883/6966309/614ee020-d958-11e4-95af-b9f63ba26d09.png)

**Comment by bokiftw** [comment]
Footer can be edited very easily from the code inside footer.php:
![screen shot 2015-04-07 at 10 51 28](https://cloud.githubusercontent.com/assets/5833593/7019867/8edc0990-dd14-11e4-9858-846c6452715b.png)

**Comment by diplomod** [comment]
OK - but I can't write code. I need an admin option for dummies.
Is that possible?

**Comment by bokiftw** [comment]
Okay I made this editable from the wordpress panel. Just go to Appearance > Widgets. You will see the 3 footer widgets areas. There is a text input and the HTML for the links you want. I made it for Network, Quicklinks and Categories. It is easy for use, you will notice.

![screen shot 2015-04-20 at 14 48 08](https://cloud.githubusercontent.com/assets/5833593/7230335/0be35666-e76d-11e4-880c-123bfff4f140.png)

**Comment by diplomod** [comment]
I found it, works basically.
- How do I change the content in "Contact"?
- Where do I connect the sction "NYHETSBREV" (Newsletter) with our Mailchimp?
- Can I cange the section Newsletter?

**Comment by bokiftw** [comment]
I also prepared this and updated on dokuhl server. I put the text structure you will need to follow, you can see in the widgets. 

I will need to edit this to make Contact editable. Will do it and update it to server. Also for this Newsletter I will need to contact backend guys since they implemented news feed.

**Comment by diplomod** [comment]
ok, thanks. @lukassiedel Your expertise is needed

**Comment by diplomod** [comment]
OK, I can edit it now, great.

2 questions left @lukassiedel 
1) How can I change this newsletter source?
![screen shot 2015-05-07 at 17 25 44](https://cloud.githubusercontent.com/assets/7487883/7518952/6c51112c-f4de-11e4-90bc-e35b28fd7bcc.png)

2) How can I edit the content of the last line
![screen shot 2015-05-07 at 17 27 03](https://cloud.githubusercontent.com/assets/7487883/7518953/73ba4a78-f4de-11e4-9f5c-7f484f9cc17c.png)

**Comment by bokiftw** [comment]
![screen shot 2015-05-08 at 10 49 54](https://cloud.githubusercontent.com/assets/5833593/7534542/d4550fba-f57b-11e4-9733-5bb7a90be1f7.png)

Go to Appearance > Editor and choose footer.php on the right side. You will see at the end of the file where it says 'GEONOVA AS'. This is the easiest and most efficient way, since this won't be changed very often.

**Comment by diplomod** [comment]
@lukassiedel kuckst du... jetzt habe ich den footer zerschossen ein wenig...
Kannst du das copyright Dings wieder in die unterste Zeile packen?
![screen shot 2015-05-10 at 17 32 06](https://cloud.githubusercontent.com/assets/7487883/7554937/8de84112-f73a-11e4-94ae-3a86ff018e78.png)
