### ISSUE TITLE
Buttons translation

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#12]
How do we deal with these buttons? Can I also translate them?
![screen shot 2015-01-29 at 18 05 25](https://cloud.githubusercontent.com/assets/7487883/5962090/82a17678-a7e1-11e4-99e1-59a5ee44c23d.png)

**Comment by bokiftw** [comment]
These buttons and all other things that are not Posts or Pages, can be translated but inside the code. So you can't translate it through Wordpress when you need it, it must be initially translated. So in order I can do it, please send me all the things you want to translate with its translations in every language. For example, this red button also, or anything in footer (sponsored by, supported by, etc).

**Comment by diplomod** [comment]
OK, I guess that's not a problem as these don't change.
But do you have an overview of the buttons?

**Comment by bokiftw** [comment]
Sorry, what do you mean with the "overview of the buttons"? Do you want to list of the button label which needs to be translated in code?

**Comment by diplomod** [comment]
exactly! 
If I start, I wil miss some and it will be back and forth... :)

**Comment by bokiftw** [comment]
OK, so here is the list of the things which have to be translated from the code, since it's not only up to buttons:

Home page:
- 'utforkse nordryggenstein' button
- 'se alle' button
- 'community' heading
- 'nordryggen nyheter' heading
- sponsors headings
- footer headings (contact, network, etc..)

About page:
- links on the right (se example, kart..)
- 'les om norges fjellheimer' button
- 'les me om geologisk..' button
- 'bidra din geofunn..' button

Login page:
- USE YOUR GEONOVA ACCOUNT AND ENGAGE IN THE GEOSCIENCE COMMUNITY
- Need an account
- Forgot password
- ENTER YOUR EMAIL ADDRESS AND NAME

Submit page:
- All input fields on the page

Geofunn page:
- GEOFUNN I NÆRHETEN
- HYTTER I NÆRHETEN

**Comment by diplomod** [comment]
I translated all in an Excel table - I will send it as an email to Michael who shall forward it

**Comment by bokiftw** [comment]
This is also done. Now all the strings are translated. We just still need to translate Submit form labels, because there are some issues with the plugin. I see they are fixing it.

**Comment by diplomod** [comment]
OK - looks good so far. If I see any errors or necessary changes, I'll open a specific issue.
