### ISSUE TITLE
Show sponsor in each geofunn

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#135]
Evtl. here?

![screen shot 2015-04-11 at 18 11 47](https://cloud.githubusercontent.com/assets/7487883/7102099/3fa6a5aa-e076-11e4-86a4-f983aeb80602.png)

"sponsored by"

**Comment by bokiftw** [comment]
And you want to have a option inside the wordpress to change the images? Not from code?

**Comment by diplomod** [comment]
No necessarily - we will have one main sponsor probably, so no need to change it often.

**Comment by bokiftw** [comment]
I have done this. Honestly, it would be more difficult to make this editable in the wordpress, since you will always have to put image for every page you make. So I made it through code, and it works fine.

Just for you information, picture here is 300px of width. If should work fine with all picture sizes, just logo should be from edge to edge. You will see.

**Comment by diplomod** [comment]
Is this active allready? If yes, how can it be made visible for testing?

**Comment by bokiftw** [comment]
After Lukas answer my email I will figure out something with him.

**Comment by diplomod** [comment]
OK.

@lukassiedel @philipdomann Let's try to get these updates working today. They are supposed to work for a week now.
