### ISSUE TITLE
Link from main page (big image) to geofun

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#19]
Can we make the headline clickable, so I get to the geofunn that is shown on the main page?

![screen shot 2015-02-12 at 16 08 15](https://cloud.githubusercontent.com/assets/7487883/6169990/8bf81b0a-b2d1-11e4-92ee-4ef5a78e02b8.png)

**Comment by bokiftw** [comment]
Just to make everything clear, of this enhancement I can make that slider is getting the featured image, headline and this longitude and latitude from the Geofunn page created inside Wordpress. Then, I will implement new custom fields for what is mandatory (longitude, latitude and sub headline) which will be used when creating the page Geofunn. Also you can tell me when you need to edit from Wordpress there, maybe link?

The thing is that I can not make dynamic things work, like things getting populated from submit form =, etc.

I guess that is okay and there is no confusion?

**Comment by diplomod** [comment]
I don't quite understand what you mean.

I want to click on the title (not the red button) and get to this page:
![04_nordyggen_geofun_wordpress_comments](https://cloud.githubusercontent.com/assets/7487883/6267537/23a30582-b845-11e4-89b3-d9a35e0e8cee.jpg)

BTW: Where is this page?

**Comment by bokiftw** [comment]
Here is the link of that page: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/geofunn/

I understand what you want to achieve, but I am telling you what I can do and the way I can do it. So I can make it like that, and it will function when you create new Geofunn page, slider will take headline and other things. So in that case I will make fileds where you will put mandatory things of the slider, but other things like profile image and name and thing from the submit form I can't tell you how you will edit this since it is backend job.

**Comment by diplomod** [comment]
OK - maybe we have a misunderstainding. I expect this view for all geofunn that I generate in the admin area.
E.g. this one: http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/nigardsbreen-3/

And accordingly the link from main.

See also #57

**Comment by diplomod** [comment]
I discussed with Michael; we don't need the active connection of the geofunn view with the posts - the guys of dokuhl managed to connect these themeselves.
However, what we would need form you is to make the main image on top flexible. Currently, it's in the CSS, so it can not be dynamically changed. the idea was, however, to change the main picture if you click on one of the smaller pictures below:
![screen shot 2015-02-23 at 14 48 45](https://cloud.githubusercontent.com/assets/7487883/6328774/1f3567d2-bb6b-11e4-910f-252cf7fc58d7.png)

**Comment by bokiftw** [comment]
OK, but anyways I did this enhancements already. You can check it here - http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/en/

So logic is a bit changed, and here is how it works:
- Wordpress posts don't do anymore, they are not needed for the slider.
- You make new page.
- You must set page template as GEOFUNN
- You will have additional field like longitude and subhead and gallery (for now).
- You will need to set featured image. It is shown above like full width image. 

So that pages you have created are geofunn, and slider on the home page takes content form that pages and make it visible. And when you click on the slider it takes you to that page.

I hope I understood you correctly.

**Comment by bokiftw** [comment]
And yeah, about the cover image you asked me, it is set like css background image but form inside the code. It is better behaviour and how it shows. If backend guys need some changes they can contact me.

**Comment by diplomod** [comment]
ok - @Immoz please discuss with borjan

**Comment by diplomod** [comment]
I understand. This basically would serve the purpose.

And it is very complicated and the pages will be a total chaos once we import the geofunn.

Plus: The other picures don't work. When I click on them, tey don't show up on top.

I would definitely prefer if we have it as posts. Is there any way to do that?

**Comment by bokiftw** [comment]
Well okay, we can discuss but I don't see any problem, because this slider is now independent. You don't need to take care of it and make a new post for every picture. I think it is more practical. 
Slider only searches for all pages with template geofuun and takes their image, headings and link, and show that content. I wouldn't say it is a mess.

**Comment by diplomod** [comment]
on dokuhl, we have now created a new post type - that's easier.
