### ISSUE TITLE
Menu incomplete

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#2]
![screen shot 2015-01-23 at 17 06 09](https://cloud.githubusercontent.com/assets/7487883/5877763/2b4ce74a-a322-11e4-9430-731edce90654.png)
![screen shot 2015-01-23 at 17 08 07](https://cloud.githubusercontent.com/assets/7487883/5877794/6bdc77f8-a322-11e4-91dc-0f5a438d5c6b.png)

vs.
![screen shot 2015-01-23 at 17 07 43](https://cloud.githubusercontent.com/assets/7487883/5877786/6365b53a-a322-11e4-8477-d950b269c6e2.png)

**Comment by bokiftw** [comment]
This is now partially fixed. I added Geologi page to the sub menu and restyled the menu like in the designs. It is partially fixed because it is not translated yet and also "utforske nordrygenstein" page wasn't added to the navigation. Can you tell me which page is that, so I can add it to its place?

**Comment by diplomod** [comment]
I could just create the menu myself as soon as the pages are ready. Maybe best?

**Comment by bokiftw** [comment]
You can always edit it, and add desired pages. For example, you will have to add map page once it is done. I made the overall menu structure, so you will see how it functions.
