### ISSUE TITLE
Upload pictures in submission form max 2 MB instead of 3 MB

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#220]
When I try to upload a picture of more than 2 MB, the upload fails.
I suspect that the limit is set to 2 MB instead of 3 MB as it says in the form:

![screen shot 2015-07-20 at 09 22 49](https://cloud.githubusercontent.com/assets/7487883/8771360/0be1fa5a-2ec1-11e5-8b89-cb88cdf60eaa.png)

Please change to 3 MB.
If possible, we can also say 5 MB actually.

**Comment by bokiftw** [comment]
Hi,

I have figure out what's wrong here. The server settings are wrong and in this case needs to be changed. Now, the server side is limiting upload file to 2MB, so that's why can't upload it up to 3MB. You need firstly to extend server limit in Wordpress.

http://www.wpbeginner.com/wp-tutorials/how-to-increase-the-maximum-file-upload-size-in-wordpress/

Please, contact guys who have access to these files to change the settings.

**Comment by lukassiedel** [comment]
ist hochgesetzt

**Comment by diplomod** [comment]
Top, merci
