### ISSUE TITLE
I can't get to the main picture on home

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#34]
How do I get this view?

![00_nordyggen_home](https://cloud.githubusercontent.com/assets/7487883/6200684/96072b5a-b483-11e4-94b2-97442aacea72.jpg)

**Comment by bokiftw** [comment]
Okay, maybe this was a bug with javascript, but now it works for me. 

Also, I would like to mention that this slider shows the "featured image" and text form the Posts in Wordpress panel. In order to show slider in desired language this Post **must** translated in that language. For example, now posts are only in english language and slider is shown in EN version. I order to show in other versions, posts need to be translated. 

I hope I answered your question.

**Comment by diplomod** [comment]
Yes, got it. Thanks
