### ISSUE TITLE
Error messag in submit page

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#36]
![screen shot 2015-02-16 at 16 58 33](https://cloud.githubusercontent.com/assets/7487883/6215004/1b127582-b5fd-11e4-947c-a193db62f4f1.png)

**Comment by bokiftw** [comment]
Yeah, I told you that in the "String translation" issue. In order to translate this, I had to use a plugin. Something went wrong with the plugin, so it is showing these errors. It's not up to us, the guys who made this plugin made a mistake with new version and they need to fix this with an update or however. We should wait a bit. I can disable this, but labels in form won't be translated, just this grey text will be.

**Comment by bokiftw** [comment]
We just got an answer from the developers: 
" Unfortunately GF 1.9 does have some conflicts with GFML. Our developers are aware of this issue and are currently working with the GF team to resolve the issue. Sorry for the inconvenience, but there is no timeline I can provide as to when it will be fixed. Please hold on for more information. "

So it's their issue, unfortunately we will need to wait a bit.

**Comment by diplomod** [comment]
OK, thanks for the info - what means a bit?

Anyway, it is not possible to publish this, so it needs to be fixed or solved with an alternative.

**Comment by bokiftw** [comment]
This is now fixed and translation of submit page works.

**Comment by diplomod** [comment]
excellent, thanks!
