### ISSUE TITLE
Button to lmap main image on home

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#39]
This button should link to the map

![screen shot 2015-02-16 at 18 44 12](https://cloud.githubusercontent.com/assets/7487883/6216679/95d0c2e2-b60c-11e4-870e-e5a47d40137a.png)

**Comment by bokiftw** [comment]
This is not a bug, this can't be done now. Also it is backend side job. If I understood correctly, this will be dynamically generated when new geofunn is submitted. So this is not static, also map (map pin) will be dynamically generated so I can't do the static link. So this _must_ be done from the backend side, since it is not static content.

**Comment by diplomod** [comment]
We have a misunderstanding. This button should link to the map. Not the specific post.

The headline will link to the post.

Can you add that? see also #37

**Comment by bokiftw** [comment]
Okay, so to understand you correctly you just want to link to the overall view of the map? Similar like link of the red arrow facing down works? So you just want map to jump into the view?

**Comment by diplomod** [comment]
Correct

**Comment by bokiftw** [comment]
I have put this to link to the map view.

**Comment by diplomod** [comment]
thanks!
