### ISSUE TITLE
Geology: Change of sequence

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#53]
Is there a way how I can change the sequence of the entries?
![screen shot 2015-02-17 at 21 22 06](https://cloud.githubusercontent.com/assets/7487883/6236476/256070cc-b6eb-11e4-8120-03afe0f00c2e.png)

In other wordpress projects we have drag&drop functionality in the admin area:
![screen shot 2015-02-17 at 21 22 12](https://cloud.githubusercontent.com/assets/7487883/6236478/3178b8c4-b6eb-11e4-9d00-42c43103b77b.png)

**Comment by bokiftw** [comment]
I would like to add this is actually new feature, since it doesn't come with a Wordpress. Anyways it is done, you can check it out. For every post type you have another option at the bottom called "Re-order". Use that so you can reorder posts the way you like .
![screen shot 2015-02-18 at 17 22 48](https://cloud.githubusercontent.com/assets/5833593/6251238/0df7c95a-b793-11e4-8920-fd0809cb0662.png)

**Comment by diplomod** [comment]
Great, perfekt!
