### ISSUE TITLE
What is the ideal picture size (wide) when added in the text?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#6]
If I want to add a picture, e.g. here, what is the ideal picture size?

![screen shot 2015-01-23 at 17 31 15](https://cloud.githubusercontent.com/assets/7487883/5878253/c3531b60-a325-11e4-86c9-8c5e557c8fd1.png)

**Comment by bokiftw** [comment]
If your question is about adding a picture into about text, like you did, maximum width is ± 671px, so picture shouldn't be lower resolution, since it will be blurry. But if you put a larger picture, it is also fine, it doesn't make a sense because it will be scaled to desired dimensions without losing a quality. So just take care not to be lower than 670px wide and the height is up to your taste.

**Comment by diplomod** [comment]
OK, thanks for the info.
