### ISSUE TITLE
Different display of Instagram picture in different browsers

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#64]
Safari:
![screen shot 2015-02-25 at 11 31 21](https://cloud.githubusercontent.com/assets/7487883/6368985/2aeded06-bce2-11e4-81a7-7584cedd19b6.png)

Chrome (less hight):
![screen shot 2015-02-25 at 11 31 07](https://cloud.githubusercontent.com/assets/7487883/6368991/3531b37e-bce2-11e4-80cb-9cdb247f3c35.png)

Fireforx:
![screen shot 2015-02-25 at 11 31 00](https://cloud.githubusercontent.com/assets/7487883/6368994/41223d2a-bce2-11e4-82d8-7274424b29fa.png)

Firefox looks best. Can the others have the same hight?

**Comment by bokiftw** [comment]
First two images are different because of the slider. So, in first picture first image is showing but last not, which is opposite to the second picture. I fixed the height issue.

Now, just tell me do you want it to be slider or not? If not I will limit to few late pictures.

**Comment by bokiftw** [comment]
You can check this out, I guess it is alright.

**Comment by diplomod** [comment]
I suggest to show only th latest ones. Or can we have a slider of the latest - let's say - 30?

**Comment by bokiftw** [comment]
OKay, I made it like this now. You can check. Now it will show up to 30 pictures in slider.

**Comment by diplomod** [comment]
Thanks. But I see the most recent pictures only when I reload the page once. Can you check?

**Comment by bokiftw** [comment]
Yes, when you reload page it resets the function and pictures are shown from the beginning. I made this like slider, so you can drag and move left/right and see all the images. Also, I made it in loop so by the time images are changing and loop continues, so the very first images shows again after the last images. Check this out here - http://staging.blgrd.co/clients/geonova/nordryggen/wordpress/

Once we are fine on all the changing I will send updates source files to your backend guys.

**Comment by diplomod** [comment]
Ok - that's cool. But what happens if there are 500 pictures? Does it start
every time from the beginning?
And it should start sliding not before the users sees the pictures - when
you reload, you start at the top of the page and when you have scrolled
down to the #nordryggen section, the pictures have already finished
scrolling...

**Comment by bokiftw** [comment]
First of all, it won't be 500 images in this slider, since I restricted it to max 30 images like you said before. Also, 500 images is not a good practice for the internet traffic. Another thing, if there are 500 images on the Instagram, here will be displayed the newest 30.

And yeah, every time you reload page it starts from the beginning. Images will not finish slider, because I put sliding in loop, and it will constantly loop. So if user scrolls down, maybe he won't see immediately first image but it will appear after very last image, and so on. So, basically if user waits long enough(or slide by himself) he will be able to see all 30 images.

**Comment by diplomod** [comment]
ok - then it's fine, let's leave it :)
