### ISSUE TITLE
Where do I change the content of page "Norges Fjellheimer"?

### ISSUE THREAD

**Issue by diplomod** [diplomod/nordryggstien.no#7]
![screen shot 2015-01-23 at 17 42 30](https://cloud.githubusercontent.com/assets/7487883/5878453/505d4480-a327-11e4-979b-95d72470c7e7.png)

**Comment by bokiftw** [comment]
For this page we just implemented everything into the code, so now every changes for this page should be done inside the code. We did the all front-end (static) part, translating the designs into the code. Basically, adding the content dynamically from the Wordpress control panel, making a new post types or any other way is back-end business.

**Comment by diplomod** [comment]
So are you saying I cannot edit the content of this page?

**Comment by bokiftw** [comment]
Okay, we can change this. We are going to implement this page to the Wordpress backend like custom post types. You will be able to edit this page from Wordpress panel, and we will let you know here when it's finished. This was confusion because this wasn't clear in the beginning and I thought we are doing the static (front-end) part.

**Comment by diplomod** [comment]
OK, good. I must be able to edit. Also for Geologi

**Comment by bokiftw** [comment]
The implementation of these two pages is finished. Now you are able to change/add content through Wordpress. You can see on the left side, in sidebar, section for Mountains and Geology. There you are making posts for desired page, which will be shown. You will see all the fields with description what they are used for.

**Comment by diplomod** [comment]
Great.

2 points:

1) Can we call it "Mountain Regions" instead of "Mountains" in the admin area?
2) The idea was to have a text to each photo so that the text on the right changes when I click another photo. Now I understand that there is only one text and the photos are independent of it.

**Comment by bokiftw** [comment]
For the first thing, it is changes. Now it says "Mountain Regions".

Second, this should be defined firstly, so now it changes the whole architecture and need to be redone which would take a lot of time. Also, from this point of view, I am not sure how that could be easily done, since there are some slider restrictions and rules which should be followed.

**Comment by diplomod** [comment]
I see - it was described in the concept, but maybe it got lost. I'll discuss with michael - we'll sort it out.

**Comment by bokiftw** [comment]
Okay, we discussed and came up with some ideas. First of all, can you tell me, this sub headline and these links under, are they dynamic too or same for every picture? Are they independent from the images or that also changes while image changes? Also, do you need to change that links from the Wordpress panel?

**Comment by diplomod** [comment]
This part should be different for each picture. Picture and Subheadline+Text are always linked.
![screen shot 2015-01-30 at 15 23 24](https://cloud.githubusercontent.com/assets/7487883/5976991/1ed1e73c-a894-11e4-8fd8-2295772751d8.png)

This part is same for all - no changes with changing the picture:
![screen shot 2015-01-30 at 15 23 29](https://cloud.githubusercontent.com/assets/7487883/5976989/18d1faa2-a894-11e4-851d-64a00ed29995.png)

**Comment by bokiftw** [comment]
OK, and these links 'se alle, kart, nyheter', so you input it from the Wordpress panel?
So, would you mind if picture and all the content on the right, slide with image? We can make it like that, so when image slide it also slider the all content on the right and change it.

**Comment by diplomod** [comment]
Re links: Ideally yes, I can edit where it links to. But it's acually clear:
- "Se alle" goes to map but filters the geofunn by this geologi/fjellheim
- "Kart" goes to map
- "Nyheter" goes to home/news

Re slider: Yes, that sounds like a good idea.

BTW: Can we change the wording of "Se alle" to "Se exempler" (See examples). That would make more sense. ANd then when we click on it, you come to the map and the geologi/the fjellheim is selected! :)

**Comment by bokiftw** [comment]
We have updated this page and made necessary changes. Now this whole content slides with the image and fills the desired content, where every image has its own caption and description. In order to work, you have to input caption and description for every image when uploading them to the post. Also, take care that description doesn't need to be too long because it will push content too much under.
Also, links on the side are imported into the Wordpress fields and you can change them from the panel. Just type in desired URL.
